name: Deploy to Acquia

on:
  push:
    branches:
      - acquia-main
  pull_request:
    branches:
      - acquia-main

defaults:
  run:
    shell: bash

env:
  TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}
  BASE_BRANCH: ${{ github.base_ref }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  PRODUCTION_BRANCH: "main"
  PR_NUMBER: ${{ github.event.number }}
  TERMINUS_SITE: "drupal-govcon"
  LHCI_GITHUB_TOKEN: ${{ github.token }}
  LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  ACQUIA_SSH_PRIVATE_KEY: ${{ secrets.ACQUIA_SSH_PRIVATE_KEY }}
  ACQUIA_REPO: ${{ secrets.ACQUIA_REPO }}

jobs:
  build:
    name: Acquia Pipelines
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Cache composer cache
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-cache
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache vendor folder
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          path: ./vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

      - name: Cache drush folder
        uses: actions/cache@v3
        env:
          cache-name: cache-drush
        with:
          path: ./drush
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: setup-environment-vars
        run: |
          export CI_BRANCH=`curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.groot-preview+json" \
            "https://api.github.com/repos/${CI_PROJECT_NAME}/commits/${COMMIT_SHA}/pulls" | \
            python3 -c "import sys, json; print(json.load(sys.stdin)[0]['head']['ref'])"`

      - name: Avoid GitHub rate limit for Composer
        run: |
          composer config -g github-oauth.github.com $GITHUB_TOKEN

      - name: Prepare Artifact
        run: |
          composer install --optimize-autoloader --no-progress --no-dev

      - name: Install DDEV
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq libnss3-tools
          LATEST_DDEV_VERSION=$(curl -s https://api.github.com/repos/ddev/ddev/releases/latest | jq -r '.tag_name')
          echo "Latest DDEV version: $LATEST_DDEV_VERSION"

          DDEV_ASSET_URL=$(curl -s https://api.github.com/repos/ddev/ddev/releases/latest | jq -r '.assets[] | select(.name | test("ddev_.*_linux_amd64.deb")) | .browser_download_url')

          if [[ -z "$DDEV_ASSET_URL" ]]; then
            echo "Error: Could not find the correct DDEV .deb package"
            exit 1
          fi

          echo "Downloading: $DDEV_ASSET_URL"
          wget "$DDEV_ASSET_URL" -O ddev.deb
          sudo dpkg -i ddev.deb
          rm ddev.deb

          ddev --version
          ddev config global --instrumentation-opt-in=false --omit-containers=ddev-ssh-agent

      - name: Start DDEV
        run: ddev start

      - name: Run Frontend Production Build
        run: ddev frontend prod

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ env.ACQUIA_SSH_PRIVATE_KEY }}

      - name: Add Acquia Git remote
        run: |
          git remote add acquia ${{ env.ACQUIA_REPO }}
          git config user.name "Nitesh Sethia"
          git config user.email "nitesh@digitalpolygon.com"

      # - name: Push to Acquia
      #   run: |
      #     git push acquia acquia-main

  # vr_tests:
  #   name: Run Visual Regression Tests
  #   runs-on: ubuntu-latest
  #   needs: ["build"]
  #   steps:
  #     - name: Checkout source branch
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         ref: ${{ github.head_ref }}

  #     - name: Setup Nodejs
  #       uses: actions/setup-node@v4

  #     - name: Install Dependencies
  #       run: npm install -g netlify-cli

  #     - name: Run Tests
  #       working-directory: vrt
  #       run: |
  #         npm install
  #         npm run backstop:reference
  #         npm run backstop:test

  #     - name: Deploy to Netlify
  #       id: netlify_deploy
  #       if: always()
  #       uses: nwtgck/actions-netlify@v3.0
  #       with:
  #         publish-dir: './vrt/backstop_data'
  #         deploy-message: "Deploy from GitHub Actions"
  #         enable-pull-request-comment: false
  #         enable-commit-comment: false
  #         overwrites-pull-request-comment: false
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  #     - name: Comment Netlify URL on Pull request
  #       uses: thollander/actions-comment-pull-request@v3
  #       if: github.event_name == 'pull_request' && always()
  #       with:
  #         message: |
  #           :rocket: Visual Regression Report can be accessed at ${{ steps.netlify_deploy.outputs.deploy-url }}/${{ env.PR_NUMBER && format('pr-{0}', env.PR_NUMBER) || (env.CI_BRANCH == 'main' && 'dev' || env.CI_BRANCH) }}/html_report/
  #         pr-number: ${{ github.event.number }}
  #         comment-tag: vrt-Report
  #         mode: upsert

  # setup-performance-test:
  #   name: Performance Tests
  #   runs-on: ubuntu-latest
  #   needs: ["build"]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Use Node.js 20.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x
  #     - name: Run Lighthouse
  #       run: |
  #         npm install -g @lhci/cli
  #         lhci autorun
