name: Deploy to Acquia Dev

on:
  push:
    branches:
      - acquia-main
      - acquia-integration
  pull_request:
    branches:
      - acquia-main

defaults:
  run:
    shell: bash

env:
  GITHUB_TOKEN: ${{ github.token }}
  LHCI_GITHUB_TOKEN: ${{ github.token }}
  LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  ACQUIA_SSH_PRIVATE_KEY: ${{ secrets.ACQUIA_SSH_PRIVATE_KEY }}
  ACQUIA_REPO: ${{ secrets.ACQUIA_REPO }}

jobs:
  build:
    name: Deploy to Acquia Dev Site
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Cache composer cache
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-cache
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache vendor folder
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          path: ./vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

      - name: Cache drush folder
        uses: actions/cache@v3
        env:
          cache-name: cache-drush
        with:
          path: ./drush
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Avoid GitHub rate limit for Composer
        run: |
          composer config -g github-oauth.github.com $GITHUB_TOKEN

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ env.ACQUIA_SSH_PRIVATE_KEY }}

      - name: Add Acquia Git Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 svn-6971.prod.hosting.acquia.com >> ~/.ssh/known_hosts

      - name: Install latest Yarn
        run: corepack enable

      - name: Setup Nodejs
        uses: actions/setup-node@v4

      - name: Activate latest Yarn
        run: yarn set version stable
  
      - name: Setup Yarn
        run: npm install -g yarn

      - name: Avoid GitHub rate limit for Composer
        run: |
          composer install --no-dev --optimize-autoloader
      
      - name: Setup Git User
        uses: qoomon/actions--setup-git@v1

      - name: Deploy to Acquia Dev
        run: |
          vendor/bin/polymer artifact:deploy acquia-integration --no-interaction -v --branch="polymer-govcon-build" --commit-msg="Generated artifact from SHA $GITHUB_SHA AND GitHub Actions run ID $GITHUB_RUN_ID."

  # vr_tests:
  #   name: Run Visual Regression Tests
  #   runs-on: ubuntu-latest
  #   needs: ["build"]
  #   steps:
  #     - name: Checkout source branch
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         ref: ${{ github.head_ref }}

  #     - name: Setup Nodejs
  #       uses: actions/setup-node@v4

  #     - name: Install Dependencies
  #       run: npm install -g netlify-cli

  #     - name: Run Tests
  #       working-directory: vrt
  #       run: |
  #         npm install
  #         npm run backstop:reference
  #         npm run backstop:test

  #     - name: Deploy to Netlify
  #       id: netlify_deploy
  #       if: always()
  #       uses: nwtgck/actions-netlify@v3.0
  #       with:
  #         publish-dir: './vrt/backstop_data'
  #         deploy-message: "Deploy from GitHub Actions"
  #         enable-pull-request-comment: false
  #         enable-commit-comment: false
  #         overwrites-pull-request-comment: false
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  #     - name: Comment Netlify URL on Pull request
  #       uses: thollander/actions-comment-pull-request@v3
  #       if: github.event_name == 'pull_request' && always()
  #       with:
  #         message: |
  #           :rocket: Visual Regression Report can be accessed at ${{ steps.netlify_deploy.outputs.deploy-url }}/${{ env.PR_NUMBER && format('pr-{0}', env.PR_NUMBER) || (env.CI_BRANCH == 'main' && 'dev' || env.CI_BRANCH) }}/html_report/
  #         pr-number: ${{ github.event.number }}
  #         comment-tag: vrt-Report
  #         mode: upsert

  # setup-performance-test:
  #   name: Performance Tests
  #   runs-on: ubuntu-latest
  #   needs: ["build"]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Use Node.js 20.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x
  #     - name: Run Lighthouse
  #       run: |
  #         npm install -g @lhci/cli
  #         lhci autorun
