name: Deploy to Dev and Multidevs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}
  BASE_BRANCH: ${{ github.base_ref }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  PRODUCTION_BRANCH: "main"
  PR_NUMBER: ${{ github.event.number }}
  TERMINUS_SITE: "drupal-govcon"

jobs:
  build:
    name: Deploy to Pantheon (Dev and Multidev)
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Cache composer cache
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-cache
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache vendor folder
        uses: actions/cache@v4
        env:
          cache-name: cache-vendor
        with:
          path: ./vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

      - name: Cache drush folder
        uses: actions/cache@v3
        env:
          cache-name: cache-drush
        with:
          path: ./drush
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install Terminus Build Tools
        run: |
          terminus self:plugin:install terminus-build-tools-plugin

      - name: setup-environment-vars
        run: |
          export CI_BRANCH=`curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.groot-preview+json" \
            "https://api.github.com/repos/${CI_PROJECT_NAME}/commits/${COMMIT_SHA}/pulls" | \
            python3 -c "import sys, json; print(json.load(sys.stdin)[0]['head']['ref'])"`

      - name: Avoid GitHub rate limit for Composer
        run: |
          composer config -g github-oauth.github.com $GITHUB_TOKEN

      - name: Prepare Artifact
        run: |
          composer install --optimize-autoloader --no-progress --no-dev

      # Deploy to Pantheon
      - name: Deploy to Pantheon
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ../private.key
          chmod 600 ../private.key
          eval `ssh-agent -s`
          ssh-add ../private.key
          git config --global --add safe.directory '*'
          git config --global user.email "devops@digitalpolygon.com"
          git config --global user.name "DevOps"
          ./.ci/deploy/pantheon/dev-multidev
